module.exports = {
  CREATE: 'EFFECT_CREATE',
  UPDATE_PARAM: 'EFFECT_UPDATE_PARAM',
  TYPES: {
    GAIN_NODE: 'GainNode',
    STEREO_PANNER: 'StereoPanner'
  },
  PARAMS: {
    GAIN_NODE_VALUE: 'GAIN_NODE_VALUE',
    STEREO_PANNER_VALUE: 'STEREO_PANNER_VALUE'
  }
};
