module.exports = {
  CREATE: 'SAMPLE_CREATE',
  DESTROY: 'SAMPLE_DESTROY',
  STOP_RECORDING: 'SAMPLE_STOP_RECORDING',
  TOGGLE_LOOPING: 'SAMPLE_TOGGLE_LOOPING',

  IS_RECORDING: 'SAMPLE_IS_RECORDING',
  IS_SAVING: 'SAMPLE_IS_SAVING'
};
